# Generated by Django 3.1.1 on 2020-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Init_Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(default=10000)),
            ],
        ),
    ]
