# Generated by Django 3.1.1 on 2020-10-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0002_init_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='init_amount',
            name='bank',
            field=models.CharField(max_length=7),
        ),
    ]
