# Generated by Django 3.1.1 on 2020-10-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0005_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='stock_ticker',
        ),
    ]
