# Generated by Django 3.1.1 on 2020-10-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0006_auto_20201010_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Init_Amount',
        ),
    ]
