# Generated by Django 3.1.1 on 2020-10-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0007_delete_init_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_ticker',
            new_name='ticker',
        ),
    ]
