# Generated by Django 3.1.1 on 2020-10-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0008_auto_20201011_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
    ]
