# Generated by Django 3.1.1 on 2020-10-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0009_buystockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystockmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buystockmodel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buystockmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
