# Generated by Django 3.1.1 on 2020-10-12 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0010_auto_20201011_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buystockmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='buystockmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
