# Generated by Django 3.1.1 on 2020-10-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0011_auto_20201012_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystockmodel',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
