# Generated by Django 3.1.1 on 2020-10-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0012_auto_20201012_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystockmodel',
            name='total_value',
            field=models.FloatField(default=0),
        ),
    ]
