# Generated by Django 3.1.1 on 2020-10-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0014_auto_20201012_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystockmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='buystockmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
    ]
