# Generated by Django 3.1.1 on 2020-10-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0017_auto_20201014_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='money',
        ),
        migrations.RemoveField(
            model_name='buystockmodel',
            name='account',
        ),
        migrations.AddField(
            model_name='bank',
            name='account',
            field=models.DecimalField(decimal_places=0, default=30000.0, max_digits=15),
        ),
    ]
