# Generated by Django 3.1.1 on 2020-10-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0018_auto_20201014_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystockmodel',
            name='account',
            field=models.DecimalField(decimal_places=0, default=30000.0, max_digits=15),
        ),
    ]
