# Generated by Django 3.1.1 on 2020-10-17 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0019_buystockmodel_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystockmodel',
            name='ticker',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
