# Generated by Django 3.1.1 on 2020-10-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0020_buystockmodel_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buystockmodel',
            name='ticker',
        ),
    ]
