# Generated by Django 3.1.1 on 2020-10-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuotes', '0022_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buystockmodel',
            name='account',
        ),
    ]
